version: "3"

services:
  db:
    image: "postgres:13-alpine"
    env_file:
      - db.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - test_network

  api:
    container_name: api
    build: ./api
    image: ggndp/pro-deploy:api
    env_file:
      - api.env
    command: uvicorn API_Server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - test_network

  server:
    build: ./frontend/
    image: ggndp/pro-deploy:server
    depends_on:
      - db
      - api

    ports:
      - 3001:80
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
